/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recipes
         * @description The library, newest first; `q` keeps recipes where every word is in the title,
         *     the tags or the ingredients.
         */
        get: operations["listRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["getRecipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/ingredients/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Quantity
         * @description "Li scrivo io": the user writes a quantity the post did not give.
         */
        put: operations["setQuantity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/ingredients/{index}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Edit */
        delete: operations["clearEdit"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/by-eye": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark By Eye
         * @description "Sì, a occhio": these quantities stay unknown, and that is fine.
         */
        post: operations["markByEye"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/cooked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Cooked */
        post: operations["markCooked"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ByEyeIn */
        ByEyeIn: {
            /** Indices */
            indices: number[];
        };
        /** Completeness */
        Completeness: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial";
            /**
             * Missing
             * @description Cosa la fonte non dice, in italiano, es. 'quantità della pasta'
             */
            missing?: string[];
        };
        /** CookedOut */
        CookedOut: {
            /** Count */
            count: number;
            /** Last */
            last: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngredientView */
        IngredientView: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Original Text */
            original_text: string;
            /** Quantity */
            quantity: number | null;
            /** Unit */
            unit: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "given" | "to_taste" | "missing" | "by_eye";
            /** Base Unit */
            base_unit: ("g" | "ml" | "tsp" | "piece") | null;
            /** Base Quantity */
            base_quantity: number | null;
            /** Edited */
            edited: boolean;
        };
        /** LibraryItem */
        LibraryItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Nome Riga 1 */
            nome_riga_1: string;
            /** Nome Riga 2 */
            nome_riga_2: string | null;
            /**
             * Diet
             * @enum {string}
             */
            diet: "vegan" | "vegetarian" | "neither";
            /** Course */
            course: ("antipasto" | "primo" | "secondo" | "contorno" | "piatto unico" | "dolce" | "colazione" | "snack" | "bevanda" | "salsa") | null;
            /** Cuisine */
            cuisine: string | null;
            /**
             * To Clarify
             * @description Quantities still unknown, plus 1 if there are no steps
             */
            to_clarify: number;
            cooked: components["schemas"]["CookedOut"];
        };
        /** PhotoOut */
        PhotoOut: {
            /**
             * Src
             * @description The halftone print, path under /api/media
             */
            src: string;
            /** Original Src */
            original_src: string;
            /** Alt */
            alt: string;
            /**
             * Source
             * @description frame (from a video you sent) or screenshot
             */
            source: string;
            /** Creator */
            creator: string | null;
            /** Source Url */
            source_url: string | null;
        };
        /** QuantityIn */
        QuantityIn: {
            /** Quantity */
            quantity: number;
            /** Unit */
            unit?: string | null;
        };
        /** RecipeDetail */
        RecipeDetail: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string;
            /** Title */
            title: string;
            /** Nome Riga 1 */
            nome_riga_1: string;
            /** Nome Riga 2 */
            nome_riga_2: string | null;
            /** Descrittore */
            descrittore: string | null;
            /** Source Url */
            source_url: string | null;
            /** Author Handle */
            author_handle: string | null;
            /** Servings */
            servings: number | null;
            /** Time Minutes */
            time_minutes: number | null;
            tags: components["schemas"]["Tags"];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientView"][];
            /** Steps */
            steps: string[];
            /**
             * Still Missing
             * @description Ingredients whose quantity is still unknown
             */
            still_missing: string[];
            /** @description What the post did not say, as imported */
            completeness: components["schemas"]["Completeness"];
            /**
             * Content Source
             * @enum {string}
             */
            content_source: "caption" | "transcript" | "frames";
            cooked: components["schemas"]["CookedOut"];
            photo: components["schemas"]["PhotoOut"] | null;
            /**
             * Photo Pending
             * @description A dish photo is being made
             */
            photo_pending: boolean;
        };
        /** Tags */
        Tags: {
            /**
             * Cuisine
             * @description In italiano, es. italiana, indiana
             */
            cuisine?: string | null;
            /** Course */
            course?: ("antipasto" | "primo" | "secondo" | "contorno" | "piatto unico" | "dolce" | "colazione" | "snack" | "bevanda" | "salsa") | null;
            /**
             * Diet
             * @enum {string}
             */
            diet: "vegan" | "vegetarian" | "neither";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRecipes: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
                index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuantityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clearEdit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markByEye: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ByEyeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markCooked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
